version: '3'

services:
  nginx:
    image: ghcr.io/getimages/nginx:1.21.1-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./app/:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${NGINX_EXPOSED_PORT:-0}:80
    depends_on:
      - php

  php:
    build: ./docker/php/fpm
    image: ${APP_NAME:-app}_php
    restart: always
    working_dir: /app
    volumes:
      - ./app/:/app/
      - ~/.ssh/:/root/.ssh/
